CREATE TABLE IF NOT EXISTS visa (
    sucursal VARCHAR(10) NOT NULL,
    concepto VARCHAR(20) NOT NULL,
    mes SMALLINT NOT NULL CHECK (mes BETWEEN 1 AND 12),
    anio SMALLINT NOT NULL CHECK (anio BETWEEN 2000 AND 2100),
    importe NUMERIC(12, 2) NOT NULL,
    tipo VARCHAR(30) NOT NULL
)